language: cpp
compiler:
  - clang
sudo: false
cache: ccache
matrix:
  include:
    - os: linux
      node_js: "latest"
      install:
        - NODE=$(which node) make lint-md-build
      script:
        - NODE=$(which node) make lint-ci
    - os: linux
      install:
        - ./configure
        - make -j2 V=
      script:
        - make -j2 test-ci
before_install:
  - export CXX="ccache clang++ -Qunused-arguments"
  - export CC="ccache clang -Qunused-arguments -Wno-unknown-warning-option"
  - export JOBS=2
